# Generated by Django 4.2.7 on 2024-09-21 22:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='application',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='exegesis',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='scripture',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
