# Generated by Django 4.2.7 on 2024-09-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_application_alter_post_exegesis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='application',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='exegesis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='scripture',
            field=models.TextField(),
        ),
    ]
